In [3]:
import pandas as pd
#from dictionery
data={'Name':['alice','bob'],'age':[25,30]}
df=pd.DataFrame(data)
print(df)

    Name  age
0  alice   25
1    bob   30

In [8]:
# From list of lists 
lst = [['Alice', 25], ['Bob', 30]] 
df = pd.DataFrame(lst, columns=['Name', 'Age']) 
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [9]:
df.head()   
df.tail()   
df.info()   
# First 5 rows 
# Last 5 rows 
# Info about DataFrame 
df.describe()  # Summary statistics

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [10]:
# Column selection 
df['Name'] 
df[['Name', 'Age']] 
# Row selection by label and position 
df.loc[0] 
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [11]:
df['Gender'] = ['F', 'M']  # Add new column 
df.drop('Age', axis=1, inplace=True)  # Remove column

In [12]:
df.isnull() 
df.dropna() 
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [17]:
df.groupby('Gender')

In [20]:
#Merging And Joining
df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['Hari', 'Arya', 'Vishnu']
})
df2 = pd.DataFrame({
    'key': [1, 2, 4],
    'Age': [25, 30, 35]
})
pd.merge(df1, df2, on='key')

   key  Name  Age
0    1  Hari   25
1    2  Arya   30